name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_secure_storage: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.0
  path: ^1.8.3
  dio: ^5.3.2
  go_router: ^10.0.0
  camera: ^0.10.5+3
  geolocator: ^10.0.1
  permission_handler: ^10.4.3
  record: ^5.0.4
  audioplayers: ^5.1.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.0.3
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  uuid: ^3.0.7
  rxdart: ^0.27.7

dev_dependencies:
  flutter_secure_storage: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  drift_dev: ^2.10.0

flutter:
  uses-material-design: true
